name: Serverless Resume Creation Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  build:
    name: Install required software
    runs-on: self-hosted

    env:
      PYTHON_REQUIREMENTS_PATH: 'python-update-dns/requirements.txt'


    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ env.PYTHON_REQUIREMENTS_PATH }}

  run-terraform:
    name: Run terraform apply
    runs-on: self-hosted

    env:
      DOMAIN: 'peter.griffin-resume.com'

    needs: build

    steps:
    - name: Set DOMAIN based on branch name
      run: |
        if [ "$GITHUB_REF" != "refs/heads/main" ]; then
          echo "Setting DOMAIN for pull request"
          export DOMAIN="${{ github.event.pull_request.head.ref }}.griffin-resume.com"
        fi
      shell: bash

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var="custom_domain=${DOMAIN}"

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="custom_domain=${DOMAIN}"