name: Serverless Resume Deletion Workflow

on:
  delete:
    branches:
      - '*'

jobs:
  build:
    name: Install required software
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

  terraform-destroy:
    name: Run terraform destroy
    runs-on: self-hosted

    needs: build

    - name: Terraform Init
      run: terraform init -backend-config="key=${{ github.ref_name }}"

    - name: Terraform Destroy
      run: terraform destroy -auto-approve